### ISSUE TITLE
v0.0.2 -> 0.0.3 update fails

### ISSUE THREAD

**Issue by ghost** [varemenos/atom-toolbar-almighty#1]
I'm running 

```
    atom --version
        1.0.3-5566d54
    node -v
        v2.3.4
    npm -v
        2.12.1
```

tool-bar-almighty 0.0.2 is installed.

@ Atom UI, updates notify of tool-bar-almighty 0.0.3 availability.

UI update from tool-bar-almighty 0.0.2 -> 0.0.3 fails with

```
    Updating to “tool-bar-almighty@0.0.3” failed.Hide output…
    EACCES, unlink '/home/pgnd/.atom/packages/tool-bar-almighty/.npmignore'
```

where

```
    cat /home/pgnd/.atom/packages/tool-bar-almighty/.npmignore
        .DS_Store
        npm-debug.log
        node_modules
```

**Comment by varemenos** [comment]
`EACCES`

That seems like a filesystem access issue. Can you check the access rights for that directory? The user that's running atom and subsequently apm might not have the rights required (read/write).

Also there is no `.npmignore` in my package, that means apm tried to create it from the .gitignore file (maybe that's where it didn't get the proper access rights).

One more thing: do you install npm packages via `sudo npm install`?

**Comment by ghost** [comment]
> EACCES
> 
> That seems like a filesystem access issue. Can you check the access rights for 
> that directory? The user that's running atom and subsequently apm might not 
> have the rights required (read/write).

You're correct about it apparently being a permissions issues.

Checking, every OTHER dir in 

```
/home/pgnd/.atom/packages/
```

has ownership "pgnd:users".  For some reason, not quite sure, /home/pgnd/.atom/packages/tool-bar-almighty had "root:root"

chown'ing to "pgnd:users" fixed the issue.  Update now completes without error.

But why that's a problem ... I'm a bit confused.

Atm, I'm exec'ing atom from a KDE desktop as

```
kdesu /usr/local/bin/atom -w
```

It's supposed to have root perms -- and should not have any problem with the root perm'd dir in any case.

> Also there is no .npmignore in my package, that means apm tried to create it 
> from the .gitignore file (maybe that's where it didn't get the proper access 
> rights).

I'm not clear on what might be going on here.  Just not familiar enough with atom's project manager's internals

> One more thing: do you install npm packages via sudo npm install?

typically, yes.  from cmd line.

but I'd installed t-b-a from the UI in the first place ...

**Comment by varemenos** [comment]
I'm kind of confused by the issue myself, my first guess was that you either installed the packages via `sudo apm install` and or that you exec'd atom via `sudo atom -w` and then installed the package but it doesn't seem that way.

npm gives you the ability to define an ignore file similar to .gitignore that ignores files from the npm package. If there is no .npmignore file, the .gitignore file is used (either by being symlinked or copied, not sure).

I will go ahead and close this issue,
if you encounter this issue again, feel free to comment and I will reopen it and investigate further
