### ISSUE TITLE
Button Git Project not working since last update

### ISSUE THREAD

**Issue by Alexandredc** [varemenos/atom-toolbar-almighty#11]
Hi,

Since the last update the git project button didn''t work

**Comment by AddictArts** [comment]
This appears to be an issue with git-projects. The issues can be seen in the console. Using the the menu option or hotkey seems to bring up the list, but it is not functioning without errors.

**Comment by varemenos** [comment]
Hey @AlexandreAWE, do you still have this issue?
Sorry for the late replies but I'm currently away serving my mandatory military service

**Comment by Alexandredc** [comment]
Hi @varemenos ! No it works now ! Thx !!
