### ISSUE TITLE
Settings don't reload using a custom entries file

### ISSUE THREAD

**Issue by hvmonteiro** [varemenos/atom-toolbar-almighty#13]
When using a custom entries file with "Override default entries" option enabled, the toolbar is not reloaded/updated reflecting the changes made. 
Additionally, if we disable/enable the package, the settings remain the same, not reflecting the changes made to the file. It seems they maybe be cached by Atom editor(?).

**Comment by varemenos** [comment]
Hey @hvmonteiro,thanks for letting me know of this bug unfortunately I'm currently away serving my 9 month mandatory military service, so I'm not sure when I will be able to spend some time to get this sorted.

**Comment by hvmonteiro** [comment]
Hello,
Thanks for the reply anyway.
Have a good time, if possible. :-/

**Comment by varemenos** [comment]
I've published v0.8 which should resolve this issue.
Please check it out and let me know if you have any issues with the way I've implemented (or whether it introduced a bug).
