### ISSUE TITLE
Request : Git Control

### ISSUE THREAD

**Issue by nappa32** [varemenos/atom-toolbar-almighty#2]
I would love it if you could enable the plugin for Git Control in the tool bar. This is the only thing I'm missing from your toolbar that I regularly use.

**Comment by varemenos** [comment]
I will take a look at it and let you know. Meanwhile could you please find the command you want to add?

**Comment by nappa32** [comment]
command is : 
`git-control:toggle`

**Comment by varemenos** [comment]
Hey @nappa32, sorry the delay, I've [added this feature](https://github.com/varemenos/atom-toolbar-almighty/commit/bc6f624dfad9a7063033a1107438980299fa3f56) in the latest version (v0.1.3).
Unfortunately, I didn't find a decent icon for it so feel free to send a PR with a better suggestion.
