### ISSUE TITLE
No errors or hints if own button-file is invalid

### ISSUE THREAD

**Issue by fridde** [varemenos/atom-toolbar-almighty#22]
The recent update to 0.8.0 changed the format of the custom-buttons-file file from `.js` to `.json`, which _silently_ removed my buttons from the toolbar.

It took me quite a while to find the culprit (i.e. the update). Could you implement a warning when an invalid json is given, maybe even hinting on the change of format?

**Comment by varemenos** [comment]
Yes I will, thank you for taking the time to report this and sorry for the trouble I've caused you with the update. I was forced to do it to fix a couple of bugs (and to prevent future issues due to the loose format).

**Comment by fridde** [comment]
I totally understand the choice and I appreciate your quick answer.

Great plugin, especially since you are doing it as a volunteer! Thanks!
