### ISSUE TITLE
[Feature Request] Scope based buttons

### ISSUE THREAD

**Issue by ethernal** [varemenos/atom-toolbar-almighty#24]
Can you add ability to, beside dependency, limit buttons visibility based on scope ex. text.md could then have buttons specific to markdown editing but the same buttons are not required when editing cpp or other file types.

**Comment by varemenos** [comment]
Hi @ethernal, toolbar-almighty is based on the https://github.com/suda/tool-bar lib and it's functionality and features come from there, you should request these features there. If they get implemented feel free to reopen this issue and I will be more than glad to include them in toolbar-almighty.
