### ISSUE TITLE
[Feature Request] Dropdown button groups

### ISSUE THREAD

**Issue by ethernal** [varemenos/atom-toolbar-almighty#25]
Could we have a button group that is a dropdown (maybe with default button and onClick action and dropdown arrow integrated) so that we can group functions ex. less common git commands could be stored in button group and things like commit, rebase etc. might be separate buttons?

**Comment by varemenos** [comment]
As I mentioned in #24, these features need to be implemented upstream, if they get implemented feel free to reopen this issue and I will be more than glad to include them in toolbar-almighty.
