### ISSUE TITLE
[Feature Request] Creating more than one toolbar

### ISSUE THREAD

**Issue by ethernal** [varemenos/atom-toolbar-almighty#26]
Is it possible to have 2 toolbars ex. 1 that is on top with custom functions and another on a side with another set of custom buttons?

**Comment by varemenos** [comment]
There is an open issue in tool-bar lib for this feature (as a matter of fact, it was I that requested it). Once it get implemented I will be able to add it in this package.

https://github.com/suda/tool-bar/issues/80
