### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by AHL96** [varemenos/atom-toolbar-almighty#27]
I'd like to be able to chose what and what is not on the toolbar. I don't like having the split screen buttons. draping the tabs to another part of the screen makes more sense to me, so id like to be able to not see those buttons

**Comment by lucasvieites** [comment]
Hi AHL96, you can already do that by creating a _custom_entries.json_ file in your .atom folder.
It's a simple text file where you can remove the buttons you don't want. You can use mine as an example: http://www.codexion.com/files/custom_entries.json
