### ISSUE TITLE
Custom entries

### ISSUE THREAD

**Issue by sudofx** [varemenos/atom-toolbar-almighty#3]
Is there a way to edit tool-bar-almighty.coffee or somewhere else, so my custom edits are preserved on updates? I'm new to atom so maybe I'm missing something. Your work on this project is greatly appreciated.

**Comment by varemenos** [comment]
Unfortunately there is no way to do this but I'm planning to provide this feature in the future. If you think that something you use could fit well with the package, feel free to send a pull request

**Comment by varemenos** [comment]
Hey @sudofx, I've added basic support for custom entries in v0.4, please check https://github.com/varemenos/atom-toolbar-almighty#custom-entries

Feel free to reopen the issue if this feature isn't what you were expecting or open a new issue if you have suggestions on how to improve the feature or this package.

**Comment by PooLP** [comment]
Hi,
Not work for me ... no error on developper tools

**Comment by sudofx** [comment]
not working for me.

**Comment by varemenos** [comment]
I will take a look at it once I return from work guys, thanks for the report

**Comment by varemenos** [comment]
I've published a new version that's supposed to tackle this issue.
Can you guys update and see if the instruction from [here](https://github.com/varemenos/atom-toolbar-almighty#custom-entries) and see if you are still facing this issue?

**Comment by sudofx** [comment]
Not working... screenshot provided

![screen shot 2015-11-20 at 6 23 51 am](https://cloud.githubusercontent.com/assets/14032554/11300841/6abdcbaa-8f4f-11e5-9e86-cd6ff0895561.png)

**Comment by PooLP** [comment]
it's ok for me ... do not forget the commas (I did not wake ^^)

**Comment by sudofx** [comment]
Lol... thank you. 6:30am here. :+1:

**Comment by varemenos** [comment]
Thank you for helping me debug this, feel free to open a new issue if you have any other problems.
