### ISSUE TITLE
Open new file

### ISSUE THREAD

**Issue by pamtbaau** [varemenos/atom-toolbar-almighty#7]
Not sure why "New File" isn't standard on the toolbar...

I've added the following to entries.coffee:
`module.exports = [
    {
            type: 'button'
            tooltip: 'New File'
            callback: 'application:new-file'
            icon: 'document'
            iconset: 'ion'
     },
    etc.`

**Comment by varemenos** [comment]
Hey @pamtbaau thanks for raising this issue, I understand your need for this item but I'd like to not bloat the toolbar with items.

I left the new file action out of the selection intentionally. My reasoning had mostly to do with the way people handle the new file action and whether it was actually needed (some use the tab bar to create a new file while others use the commonly used hotkey `Ctrl` + `N`).

If you don't mind, I'd like to leave this issue open for a few weeks to see if anyone else is interested in this toolbar item.

**Comment by pamtbaau** [comment]
Hi @varemenos, yes many more items could be thought of... e.g. 'save all' to name one. And I wouldn't mind a full toolbar if well organised.

I've never been a fan of keyboard-only apps. Yes, switching from Notepad++ to Atom has its challenges for me... :-) Ditched Sublime earlier, but somehow want to try out Atom.

**Comment by varemenos** [comment]
I guess it's time to close this.
If we ever get more interest in this, I will reopen and implement it, hope you understand.

In the meantime you could use the custom entries feature to add it yourself:

https://github.com/varemenos/atom-toolbar-almighty#custom-entries
