### ISSUE TITLE
Open Terminal

### ISSUE THREAD

**Issue by rpaweb** [varemenos/atom-toolbar-almighty#8]
The icon for opens a terminal doesn't appear in the tool-bar-almighty.
Term2 package is installed, but the icon doesn't show in the toolbar.
I open the entries.coffee file, and the JSON configure doesn't have the OpenTerminal's config, and that's how even the term2 package is already installed, the OpenTerminal's icon not show up.

**Comment by varemenos** [comment]
I'm sorry, I didn't get what is actually going on.
Was this actually an issue? Did you find what you were looking for?
